# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 701f3cabe7bc1c11c18ada8cb5aaaf8471922bbe37c6f215904ac5676f59e7842faaed80925bb4afec58f3c39dd0ae4a56d82f22ab8826a4463a44f03d1aead1

test:
  secret_key_base: 299d8e56c6edde5d26c0eb31bfad5de22546ba690911e8ce983cc947025128506c3b50add8ace1ceec57bff47e3d113f0fde32ddbc187d7e3f7a896f9a27c124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
